// Copyright (C) 2026 SharpEmu Emulator Project
// Copyright (C) 2026 craze1pirate - CraziiEmu Project
// SPDX-License-Identifier: GPL-2.0-or-later

using System;
using System.Buffers.Binary;
using CraziiEmu.Core.HLE;
using CraziiEmu.Core.Loader;
using CraziiEmu.Core.Memory;
using CraziiEmu.HLE;
using Iced.Intel;

namespace CraziiEmu.Core.Cpu;

/// <summary>
/// A minimal headless x86-64 execution engine that loops through instructions in virtual memory,
/// decodes them using Iced, and updates the CPU context.
/// </summary>
public class EmulatorEngine
{
    private readonly VirtualMemoryManager _memory;
    private readonly SyscallRouter _syscallRouter;
    private readonly CpuContext _context;

    /// <summary>
    /// Gets or sets the DynamicLinker for resolving HLE stub addresses.
    /// </summary>
    public CraziiEmu.Core.Loader.DynamicLinker? DynamicLinker { get; set; }

    /// <summary>
    /// Gets or sets the ModuleManager for executing registered HLE delegates.
    /// </summary>
    public IModuleManager? ModuleManager { get; set; }

    /// <summary>
    /// Gets or sets the import stubs generated by the SelfLoader (Address -> Symbol NID).
    /// </summary>
    public IReadOnlyDictionary<ulong, string>? SelfImportStubs { get; set; }

    // We need a dummy ICpuMemory to satisfy CpuContext constructor constraint.
    // The engine itself uses VirtualMemoryManager directly for instruction fetches.


    /// <summary>
    /// CodeReader implementation that reads bytes from VirtualMemoryManager.
    /// </summary>
    private class MemoryCodeReader : CodeReader
    {
        private readonly VirtualMemoryManager _memory;
        private ulong _rip;

        public MemoryCodeReader(VirtualMemoryManager memory, ulong rip)
        {
            _memory = memory;
            _rip = rip;
        }

        public override int ReadByte()
        {
            try
            {
                byte b = _memory.GetSpan(_rip, 1)[0];
                _rip++;
                return b;
            }
            catch (ArgumentOutOfRangeException)
            {
                return -1;
            }
        }
    }

    /// <summary>
    /// Gets the active CPU context representing the register states.
    /// </summary>
    public CpuContext Context => _context;

    /// <summary>
    /// Initializes a new instance of the <see cref="EmulatorEngine"/> class.
    /// </summary>
    /// <param name="memory">The virtual memory manager instance.</param>
    /// <param name="syscallRouter">The system call router instance.</param>
    public EmulatorEngine(VirtualMemoryManager memory, SyscallRouter syscallRouter)
    {
        _memory = memory ?? throw new ArgumentNullException(nameof(memory));
        _syscallRouter = syscallRouter ?? throw new ArgumentNullException(nameof(syscallRouter));
        
        // Match standard ELF assumption by configuring the Syscall Abi
        _syscallRouter.ActiveAbi = SyscallAbi.FreeBsd;

        // Note: We use Gen5 generically for Orbis/Prospero as discovered earlier.
        _context = new CpuContext(new VmmAdapter(memory), Generation.Gen5);
    }

    private int _instructionCount = 0;

    /// <summary>
    /// Runs the execution loop either on the current thread or across parallel tasks.
    /// </summary>
    public void Run()
    {
        var config = CraziiEmu.HLE.Configuration.CraziiEmuConfig.Instance;
        bool limitSpeed = config.LimitSpeed;
        bool multicore = config.EnableMulticore;

        if (multicore)
        {
            int coreCount = Environment.ProcessorCount > 1 ? Environment.ProcessorCount / 2 : 2;
            System.Threading.Tasks.Task[] tasks = new System.Threading.Tasks.Task[coreCount];
            for (int i = 0; i < coreCount; i++)
            {
                tasks[i] = System.Threading.Tasks.Task.Run(() => ExecutionLoop(limitSpeed));
            }
            System.Threading.Tasks.Task.WaitAll(tasks);
        }
        else
        {
            ExecutionLoop(limitSpeed);
        }
    }

    private void ExecutionLoop(bool limitSpeed)
    {
        long targetTicksPerStep = System.Diagnostics.Stopwatch.Frequency / 3_000_000; // e.g. 3 MHz limit
        long nextTick = System.Diagnostics.Stopwatch.GetTimestamp();

        while (!_context.IsTerminated)
        {
            if (limitSpeed)
            {
                long currentTick = System.Diagnostics.Stopwatch.GetTimestamp();
                if (currentTick < nextTick)
                {
                    System.Threading.Thread.SpinWait(10);
                    continue;
                }
                nextTick = currentTick + targetTicksPerStep;
            }

            Step();
        }
    }

    /// <summary>
    /// Executes exactly one instruction step.
    /// </summary>
    public void Step()
    {
        if (_context.IsTerminated)
        {
            return;
        }

        ulong rip = _context.Rip;
        
        // Create Iced decoder reading from VirtualMemoryManager
        var codeReader = new MemoryCodeReader(_memory, rip);
        var decoder = Decoder.Create(64, codeReader, rip, DecoderOptions.None);
        decoder.Decode(out Instruction instruction);

        if (_instructionCount < 30)
        {
            Console.WriteLine($"[CPU] Executing: 0x{rip:X16} - {instruction}");
            _instructionCount++;
        }

        if (instruction.IsInvalid)
        {
            // If invalid, we throw using the first byte at RIP for compatibility with existing tests
            byte firstByte = 0;
            try { firstByte = _memory.GetSpan(rip, 1)[0]; } catch { }
            throw new InvalidOpcodeException(rip, firstByte);
        }

        switch (instruction.Mnemonic)
        {
            case Mnemonic.Syscall:
                _context[CraziiEmu.HLE.CpuRegister.Rcx] = instruction.NextIP;
                _context[CraziiEmu.HLE.CpuRegister.R11] = _context.Rflags;
                _syscallRouter.Dispatch(_context);
                break;

            case Mnemonic.Jmp:
                if (instruction.Op0Kind == OpKind.NearBranch64 || instruction.Op0Kind == OpKind.NearBranch32) 
                    _context.Rip = instruction.NearBranchTarget;
                else if (instruction.Op0Kind == OpKind.Register) 
                    _context.Rip = GetRegister(instruction.Op0Register);
                else if (instruction.Op0Kind == OpKind.Memory) 
                    _context.Rip = System.Buffers.Binary.BinaryPrimitives.ReadUInt64LittleEndian(_memory.GetSpan(GetMemoryAddress(ref instruction), 8));
                else 
                    throw new Exception($"Unsupported JMP operand kind: {instruction.Op0Kind}");
                return; // Do not advance RIP by instruction length

            case Mnemonic.Mov:
                HandleMov(ref instruction);
                break;

            case Mnemonic.Add:
                HandleAdd(ref instruction);
                break;

            case Mnemonic.Sub:
                HandleSub(ref instruction);
                break;

            case Mnemonic.Xor:
                HandleXor(ref instruction);
                break;

            case Mnemonic.Xchg:
                HandleXchg(ref instruction);
                break;

            case Mnemonic.Or:
                HandleOr(ref instruction);
                break;

            case Mnemonic.Push:
                HandlePush(ref instruction);
                break;

            case Mnemonic.Pop:
                HandlePop(ref instruction);
                break;

            case Mnemonic.Cmp:
                HandleCmp(ref instruction);
                break;

            case Mnemonic.Jl:
                if (HandleConditionalJump(ref instruction, _context.SignFlag != _context.OverflowFlag))
                    return;
                break;

            case Mnemonic.Jge:
                if (HandleConditionalJump(ref instruction, _context.SignFlag == _context.OverflowFlag))
                    return;
                break;

            case Mnemonic.Jne:
                if (HandleConditionalJump(ref instruction, !_context.ZeroFlag))
                    return;
                break;

            case Mnemonic.Nop:
            case Mnemonic.Endbr64:
                break; // Do nothing
                
            case Mnemonic.Lea:
                HandleLea(ref instruction);
                break;

            case Mnemonic.Ret:
                HandleRet(ref instruction);
                return; // Do not advance RIP

            case Mnemonic.Call:
                HandleCall(ref instruction);
                return; // Do not advance RIP

            case Mnemonic.And:
                HandleAnd(ref instruction);
                break;

            case Mnemonic.Test:
                HandleTest(ref instruction);
                break;


            case Mnemonic.Shrx:
                HandleShrx(ref instruction);
                break;
            case Mnemonic.Bextr:
                HandleBextr(ref instruction);
                break;

            case Mnemonic.Shlx:
                HandleShlx(ref instruction);
                break;

            case Mnemonic.Shl:
            case Mnemonic.Sal:
                HandleShl(ref instruction);
                break;

            case Mnemonic.Shr:
                HandleShr(ref instruction);
                break;

            case Mnemonic.Sar:
                HandleSar(ref instruction);
                break;

            case Mnemonic.Movzx:
                HandleMovzx(ref instruction);
                break;

            case Mnemonic.Movsxd:
                HandleMovsxd(ref instruction);
                break;

            case Mnemonic.Imul:
                HandleImul(ref instruction);
                break;

            case Mnemonic.Mul:
                HandleMul(ref instruction);
                break;

            case Mnemonic.Lzcnt:
                HandleLzcnt(ref instruction);
                break;

            case Mnemonic.Div:
                HandleDiv(ref instruction);
                break;

            case Mnemonic.Inc:
                HandleInc(ref instruction);
                break;

            case Mnemonic.Dec:
                HandleDec(ref instruction);
                break;

            case Mnemonic.Neg:
                HandleNeg(ref instruction);
                break;

            case Mnemonic.Not:
                HandleNot(ref instruction);
                break;

            case Mnemonic.Cdqe:
                HandleCdqe(ref instruction);
                break;

            case Mnemonic.Je:
                if (HandleConditionalJump(ref instruction, _context.ZeroFlag))
                    return;
                break;

            case Mnemonic.Jle:
                if (HandleConditionalJump(ref instruction, _context.ZeroFlag || _context.SignFlag != _context.OverflowFlag))
                    return;
                break;

            case Mnemonic.Jg:
                if (HandleConditionalJump(ref instruction, !_context.ZeroFlag && _context.SignFlag == _context.OverflowFlag))
                    return;
                break;

            case Mnemonic.Ja:
                if (HandleConditionalJump(ref instruction, !_context.CarryFlag && !_context.ZeroFlag))
                    return;
                break;

            case Mnemonic.Jb:
                if (HandleConditionalJump(ref instruction, _context.CarryFlag))
                    return;
                break;

            case Mnemonic.Jbe:
                if (HandleConditionalJump(ref instruction, _context.CarryFlag || _context.ZeroFlag))
                    return;
                break;

            case Mnemonic.Jae:
                if (HandleConditionalJump(ref instruction, !_context.CarryFlag))
                    return;
                break;

            case Mnemonic.Vmovaps:
            case Mnemonic.Movaps:
            case Mnemonic.Vmovups:
            case Mnemonic.Movups:
            case Mnemonic.Vmovdqu:
            case Mnemonic.Movdqu:
            case Mnemonic.Vmovdqa:
            case Mnemonic.Movdqa:
                HandleVmovaps(ref instruction);
                break;

            case Mnemonic.Vmovhps:
            case Mnemonic.Movhps:
                HandleVmovhps(ref instruction);
                break;

            case Mnemonic.Vmovd:
            case Mnemonic.Movd:
            case Mnemonic.Vmovq:
            case Mnemonic.Movq:
                HandleVmovd(ref instruction);
                break;

            case Mnemonic.Vpcmpeqd:
            case Mnemonic.Pcmpeqd:
                HandleVpcmpeqd(ref instruction);
                break;

            case Mnemonic.Vbroadcastss:
            case Mnemonic.Vbroadcastsd:
                HandleVbroadcast(ref instruction);
                break;

            case Mnemonic.Vpextrq:
            case Mnemonic.Pextrq:
                HandleVpextrq(ref instruction);
                break;

            case Mnemonic.Vxorps:
            case Mnemonic.Vpxor:
            case Mnemonic.Vpxord:
            case Mnemonic.Vpxorq:
                HandleVxorps(ref instruction);
                break;

            case Mnemonic.Movbe:
                HandleMovbe(ref instruction);
                break;

            case Mnemonic.Andn:
                HandleAndn(ref instruction);
                break;

            case Mnemonic.Rorx:
                HandleRorx(ref instruction);
                break;

            case Mnemonic.Js:
                if (HandleConditionalJump(ref instruction, _context.SignFlag))
                    return;
                break;

            case Mnemonic.Jns:
                if (HandleConditionalJump(ref instruction, !_context.SignFlag))
                    return;
                break;

            case Mnemonic.Jo:
                if (HandleConditionalJump(ref instruction, _context.OverflowFlag))
                    return;
                break;

            case Mnemonic.Jno:
                if (HandleConditionalJump(ref instruction, !_context.OverflowFlag))
                    return;
                break;


            case Mnemonic.Cmovb:
                HandleConditionalMove(ref instruction, _context.CarryFlag);
                break;
            case Mnemonic.Cmovae:
                HandleConditionalMove(ref instruction, !_context.CarryFlag);
                break;
            case Mnemonic.Cmove:
                HandleConditionalMove(ref instruction, _context.ZeroFlag);
                break;
            case Mnemonic.Cmovne:
                HandleConditionalMove(ref instruction, !_context.ZeroFlag);
                break;
            case Mnemonic.Cmovbe:
                HandleConditionalMove(ref instruction, _context.CarryFlag || _context.ZeroFlag);
                break;
            case Mnemonic.Cmova:
                HandleConditionalMove(ref instruction, !_context.CarryFlag && !_context.ZeroFlag);
                break;
            case Mnemonic.Cmovs:
                HandleConditionalMove(ref instruction, _context.SignFlag);
                break;
            case Mnemonic.Cmovns:
                HandleConditionalMove(ref instruction, !_context.SignFlag);
                break;
            case Mnemonic.Cmovp:
                HandleConditionalMove(ref instruction, false); // Parity not fully supported yet
                break;
            case Mnemonic.Cmovnp:
                HandleConditionalMove(ref instruction, true); // Parity not fully supported yet
                break;
            case Mnemonic.Cmovl:
                HandleConditionalMove(ref instruction, _context.SignFlag != _context.OverflowFlag);
                break;
            case Mnemonic.Cmovge:
                HandleConditionalMove(ref instruction, _context.SignFlag == _context.OverflowFlag);
                break;
            case Mnemonic.Cmovle:
                HandleConditionalMove(ref instruction, _context.ZeroFlag || (_context.SignFlag != _context.OverflowFlag));
                break;
            case Mnemonic.Cmovg:
                HandleConditionalMove(ref instruction, !_context.ZeroFlag && (_context.SignFlag == _context.OverflowFlag));
                break;
            case Mnemonic.Cmovo:
                HandleConditionalMove(ref instruction, _context.OverflowFlag);
                break;
            case Mnemonic.Cmovno:
                HandleConditionalMove(ref instruction, !_context.OverflowFlag);
                break;


            case Mnemonic.Setb:
                HandleSetcc(ref instruction, _context.CarryFlag);
                break;
            case Mnemonic.Setae:
                HandleSetcc(ref instruction, !_context.CarryFlag);
                break;
            case Mnemonic.Sete:
                HandleSetcc(ref instruction, _context.ZeroFlag);
                break;
            case Mnemonic.Setne:
                HandleSetcc(ref instruction, !_context.ZeroFlag);
                break;
            case Mnemonic.Setbe:
                HandleSetcc(ref instruction, _context.CarryFlag || _context.ZeroFlag);
                break;
            case Mnemonic.Seta:
                HandleSetcc(ref instruction, !_context.CarryFlag && !_context.ZeroFlag);
                break;
            case Mnemonic.Sets:
                HandleSetcc(ref instruction, _context.SignFlag);
                break;
            case Mnemonic.Setns:
                HandleSetcc(ref instruction, !_context.SignFlag);
                break;
            case Mnemonic.Setp:
                HandleSetcc(ref instruction, false); // Parity not fully supported yet
                break;
            case Mnemonic.Setnp:
                HandleSetcc(ref instruction, true); // Parity not fully supported yet
                break;
            case Mnemonic.Setl:
                HandleSetcc(ref instruction, _context.SignFlag != _context.OverflowFlag);
                break;
            case Mnemonic.Setge:
                HandleSetcc(ref instruction, _context.SignFlag == _context.OverflowFlag);
                break;
            case Mnemonic.Setle:
                HandleSetcc(ref instruction, _context.ZeroFlag || (_context.SignFlag != _context.OverflowFlag));
                break;
            case Mnemonic.Setg:
                HandleSetcc(ref instruction, !_context.ZeroFlag && (_context.SignFlag == _context.OverflowFlag));
                break;
            case Mnemonic.Seto:
                HandleSetcc(ref instruction, _context.OverflowFlag);
                break;
            case Mnemonic.Setno:
                HandleSetcc(ref instruction, !_context.OverflowFlag);
                break;

            case Mnemonic.Int3:
                HandleInt3(ref instruction);
                return;
            case Mnemonic.Ud2:
                throw new Exception($"UD2 executed (Game Abort/Panic) at RIP 0x{rip:X16}. Check standard output for preceding errors or invalid handle returns.");

            default:
                throw new Exception($"Unimplemented mnemonic '{instruction.Mnemonic}' (first byte 0x{_memory.GetSpan(rip, 1)[0]:X2}) at RIP 0x{rip:X16}");
        }

        _context.Rip += (ulong)instruction.Length;
    }

    private void HandleMov(ref Instruction instruction)
    {
        var op0Kind = instruction.Op0Kind;
        var op1Kind = instruction.Op1Kind;

        ulong srcValue = 0;

        if (op1Kind == OpKind.Register)
        {
            srcValue = GetRegister(instruction.Op1Register);
        }
        else if (IsImmediate(op1Kind))
        {
            srcValue = instruction.GetImmediate(1);
        }
        else if (op1Kind == OpKind.Memory)
        {
            ulong srcAddr = GetMemoryAddress(ref instruction);
            srcValue = ReadMemory(ref instruction, srcAddr);
        }
        else
        {
            throw new InvalidOpcodeException(_context.Rip, 0); // Simulate unsupported
        }

        if (op0Kind == OpKind.Register)
        {
            SetRegister(instruction.Op0Register, srcValue);
        }
        else if (op0Kind == OpKind.Memory)
        {
            ulong address = GetMemoryAddress(ref instruction);
            WriteMemory(ref instruction, address, srcValue);
        }
        else
        {
            throw new InvalidOpcodeException(_context.Rip, 0);
        }
    }

    private void HandleMovbe(ref Instruction instruction)
    {
        var op0Kind = instruction.Op0Kind;
        var op1Kind = instruction.Op1Kind;

        if (op0Kind == OpKind.Register && op1Kind == OpKind.Memory)
        {
            ulong srcAddr = GetMemoryAddress(ref instruction);
            srcAddr = TranslateAddress(srcAddr);
            int size = instruction.Op0Register.GetSize();
            var span = _memory.GetSpan(srcAddr, size);
            ulong value = 0;

            if (size == 2)
                value = BinaryPrimitives.ReadUInt16BigEndian(span);
            else if (size == 4)
                value = BinaryPrimitives.ReadUInt32BigEndian(span);
            else if (size == 8)
                value = BinaryPrimitives.ReadUInt64BigEndian(span);
            else
                throw new InvalidOpcodeException(_context.Rip, 0);

            SetRegister(instruction.Op0Register, value);
        }
        else if (op0Kind == OpKind.Memory && op1Kind == OpKind.Register)
        {
            ulong dstAddr = GetMemoryAddress(ref instruction);
            dstAddr = TranslateAddress(dstAddr);
            int size = instruction.Op1Register.GetSize();
            ulong value = GetRegister(instruction.Op1Register);
            var span = _memory.GetSpan(dstAddr, size);

            if (size == 2)
                BinaryPrimitives.WriteUInt16BigEndian(span, (ushort)value);
            else if (size == 4)
                BinaryPrimitives.WriteUInt32BigEndian(span, (uint)value);
            else if (size == 8)
                BinaryPrimitives.WriteUInt64BigEndian(span, value);
            else
                throw new InvalidOpcodeException(_context.Rip, 0);
        }
        else
        {
            throw new InvalidOpcodeException(_context.Rip, 0);
        }
    }

    private void HandleAndn(ref Instruction instruction)
    {
        ulong src1 = GetRegister(instruction.Op1Register);
        ulong src2 = 0;

        if (instruction.Op2Kind == OpKind.Register)
        {
            src2 = GetRegister(instruction.Op2Register);
        }
        else if (instruction.Op2Kind == OpKind.Memory)
        {
            ulong src2Addr = GetMemoryAddress(ref instruction);
            src2 = ReadMemory(ref instruction, src2Addr);
        }
        else
        {
            throw new InvalidOpcodeException(_context.Rip, 0);
        }

        ulong result = (~src1) & src2;

        int size = instruction.Op0Register.GetSize();
        if (size == 4)
            result = (uint)result;
        else if (size == 2)
            result = (ushort)result;
        else if (size == 1)
            result = (byte)result;

        SetRegister(instruction.Op0Register, result);

        _context.ZeroFlag = result == 0;
        _context.SignFlag = (result & (1UL << (size * 8 - 1))) != 0;
        _context.CarryFlag = false;
        _context.OverflowFlag = false;
    }

    private void HandleRorx(ref Instruction instruction)
    {
        ulong src = 0;
        if (instruction.Op1Kind == OpKind.Register)
        {
            src = GetRegister(instruction.Op1Register);
        }
        else if (instruction.Op1Kind == OpKind.Memory)
        {
            ulong srcAddr = GetMemoryAddress(ref instruction);
            src = ReadMemory(ref instruction, srcAddr);
        }
        else
        {
            throw new InvalidOpcodeException(_context.Rip, 0);
        }

        int shift = (int)instruction.GetImmediate(2);
        int size = instruction.Op0Register.GetSize();
        
        ulong result = 0;
        if (size == 4)
        {
            uint val = (uint)src;
            shift &= 0x1F;
            result = (val >> shift) | (val << (32 - shift));
        }
        else if (size == 8)
        {
            shift &= 0x3F;
            result = (src >> shift) | (src << (64 - shift));
        }
        else if (size == 2)
        {
            ushort val = (ushort)src;
            shift &= 0x0F;
            result = (ushort)((val >> shift) | (val << (16 - shift)));
        }
        else
        {
            throw new InvalidOpcodeException(_context.Rip, 0);
        }

        SetRegister(instruction.Op0Register, result);
        // RORX does NOT affect flags.
    }

    private void HandleXchg(ref Instruction instruction)
    {
        var op0Kind = instruction.Op0Kind;
        var op1Kind = instruction.Op1Kind;

        ulong val0, val1;

        if (op0Kind == OpKind.Register)
            val0 = GetRegister(instruction.Op0Register);
        else if (op0Kind == OpKind.Memory)
            val0 = ReadMemory(ref instruction, GetMemoryAddress(ref instruction));
        else
            throw new InvalidOpcodeException(_context.Rip, 0);

        if (op1Kind == OpKind.Register)
            val1 = GetRegister(instruction.Op1Register);
        else if (op1Kind == OpKind.Memory)
            val1 = ReadMemory(ref instruction, GetMemoryAddress(ref instruction));
        else
            throw new InvalidOpcodeException(_context.Rip, 0);

        if (op0Kind == OpKind.Register)
            SetRegister(instruction.Op0Register, val1);
        else if (op0Kind == OpKind.Memory)
            WriteMemory(ref instruction, GetMemoryAddress(ref instruction), val1);

        if (op1Kind == OpKind.Register)
            SetRegister(instruction.Op1Register, val0);
        else if (op1Kind == OpKind.Memory)
            WriteMemory(ref instruction, GetMemoryAddress(ref instruction), val0);
    }

    private void HandleVxorps(ref Instruction instruction)
    {
        var op0Kind = instruction.Op0Kind;
        var op1Kind = instruction.Op1Kind;
        var op2Kind = instruction.Op2Kind;

        if (op0Kind == OpKind.Register && op1Kind == OpKind.Register && op2Kind == OpKind.Register)
        {
            int dstReg = GetVectorRegisterIndex(instruction.Op0Register, out bool isYmm);
            int src1Reg = GetVectorRegisterIndex(instruction.Op1Register, out _);
            int src2Reg = GetVectorRegisterIndex(instruction.Op2Register, out _);

            _context.GetXmmRegister(src1Reg, out ulong s1L, out ulong s1H);
            _context.GetXmmRegister(src2Reg, out ulong s2L, out ulong s2H);

            ulong resL = s1L ^ s2L;
            ulong resH = s1H ^ s2H;

            _context.SetXmmRegister(dstReg, resL, resH);

            if (isYmm)
            {
                _context.GetYmmUpper(src1Reg, out ulong s1HL, out ulong s1HH);
                _context.GetYmmUpper(src2Reg, out ulong s2HL, out ulong s2HH);
                _context.SetYmmUpper(dstReg, s1HL ^ s2HL, s1HH ^ s2HH);
            }
            else
            {
                _context.ClearYmmUpper(dstReg);
            }
        }
        else
        {
            throw new Exception($"Unsupported Vxorps operands: {op0Kind}, {op1Kind}, {op2Kind}");
        }
    }

    private void HandleVmovaps(ref Instruction instruction)
    {
        var op0Kind = instruction.Op0Kind;
        var op1Kind = instruction.Op1Kind;

        if (op0Kind == OpKind.Register && op1Kind == OpKind.Memory)
        {
            ulong srcAddr = GetMemoryAddress(ref instruction);
            int regIndex = GetVectorRegisterIndex(instruction.Op0Register, out bool isYmm);
            
            var span = _memory.GetSpan(srcAddr, isYmm ? 32 : 16);
            ulong lowLow = BinaryPrimitives.ReadUInt64LittleEndian(span.Slice(0, 8));
            ulong lowHigh = BinaryPrimitives.ReadUInt64LittleEndian(span.Slice(8, 8));
            
            _context.SetXmmRegister(regIndex, lowLow, lowHigh);
            if (isYmm)
            {
                ulong highLow = BinaryPrimitives.ReadUInt64LittleEndian(span.Slice(16, 8));
                ulong highHigh = BinaryPrimitives.ReadUInt64LittleEndian(span.Slice(24, 8));
                _context.SetYmmUpper(regIndex, highLow, highHigh);
            }
            else
            {
                if (instruction.Mnemonic == Mnemonic.Vmovaps || instruction.Mnemonic == Mnemonic.Vmovups || instruction.Mnemonic == Mnemonic.Vmovdqu || instruction.Mnemonic == Mnemonic.Vmovdqa)
                    _context.ClearYmmUpper(regIndex);
            }
        }
        else if (op0Kind == OpKind.Memory && op1Kind == OpKind.Register)
        {
            ulong dstAddr = GetMemoryAddress(ref instruction);
            int regIndex = GetVectorRegisterIndex(instruction.Op1Register, out bool isYmm);

            var span = _memory.GetSpan(dstAddr, isYmm ? 32 : 16);
            _context.GetXmmRegister(regIndex, out ulong lowLow, out ulong lowHigh);
            BinaryPrimitives.WriteUInt64LittleEndian(span.Slice(0, 8), lowLow);
            BinaryPrimitives.WriteUInt64LittleEndian(span.Slice(8, 8), lowHigh);

            if (isYmm)
            {
                _context.GetYmmUpper(regIndex, out ulong highLow, out ulong highHigh);
                BinaryPrimitives.WriteUInt64LittleEndian(span.Slice(16, 8), highLow);
                BinaryPrimitives.WriteUInt64LittleEndian(span.Slice(24, 8), highHigh);
            }
        }
        else if (op0Kind == OpKind.Register && op1Kind == OpKind.Register)
        {
            int dstReg = GetVectorRegisterIndex(instruction.Op0Register, out bool dstIsYmm);
            int srcReg = GetVectorRegisterIndex(instruction.Op1Register, out bool srcIsYmm);

            _context.GetXmmRegister(srcReg, out ulong lowLow, out ulong lowHigh);
            _context.SetXmmRegister(dstReg, lowLow, lowHigh);

            if (dstIsYmm && srcIsYmm)
            {
                _context.GetYmmUpper(srcReg, out ulong highLow, out ulong highHigh);
                _context.SetYmmUpper(dstReg, highLow, highHigh);
            }
            else
            {
                if (instruction.Mnemonic == Mnemonic.Vmovaps || instruction.Mnemonic == Mnemonic.Vmovups || instruction.Mnemonic == Mnemonic.Vmovdqu || instruction.Mnemonic == Mnemonic.Vmovdqa)
                    _context.ClearYmmUpper(dstReg);
            }
        }
        else
        {
            throw new InvalidOpcodeException(_context.Rip, 0);
        }
    }

    private void HandleVmovhps(ref Instruction instruction)
    {
        var op0Kind = instruction.Op0Kind;
        var op1Kind = instruction.Op1Kind;
        var op2Kind = instruction.Op2Kind;

        if (op0Kind == OpKind.Register && op1Kind == OpKind.Register && op2Kind == OpKind.Memory)
        {
            int dstReg = GetVectorRegisterIndex(instruction.Op0Register, out _);
            int srcReg = GetVectorRegisterIndex(instruction.Op1Register, out _);
            ulong memAddr = GetMemoryAddress(ref instruction);

            _context.GetXmmRegister(srcReg, out ulong lowLow, out _);
            ulong memVal = ReadMemory(ref instruction, memAddr); // OpKind.Memory, size is 8 bytes (64 bits)

            _context.SetXmmRegister(dstReg, lowLow, memVal);
            if (instruction.Mnemonic == Mnemonic.Vmovhps)
                _context.ClearYmmUpper(dstReg);
        }
        else if (op0Kind == OpKind.Register && op1Kind == OpKind.Memory)
        {
            // Legacy Movhps xmm1, m64
            int dstReg = GetVectorRegisterIndex(instruction.Op0Register, out _);
            ulong memAddr = GetMemoryAddress(ref instruction);

            _context.GetXmmRegister(dstReg, out ulong lowLow, out _);
            ulong memVal = ReadMemory(ref instruction, memAddr); // 8 bytes

            _context.SetXmmRegister(dstReg, lowLow, memVal);
        }
        else if (op0Kind == OpKind.Memory && op1Kind == OpKind.Register)
        {
            // Movhps m64, xmm1 or Vmovhps m64, xmm1
            ulong dstAddr = GetMemoryAddress(ref instruction);
            int srcReg = GetVectorRegisterIndex(instruction.Op1Register, out _);

            _context.GetXmmRegister(srcReg, out _, out ulong lowHigh);
            WriteMemory(ref instruction, dstAddr, lowHigh);
        }
        else
        {
            throw new Exception($"Unsupported Vmovhps operands: {op0Kind}, {op1Kind}, {op2Kind}");
        }
    }

    private void HandleVmovd(ref Instruction instruction)
    {
        var op0Kind = instruction.Op0Kind;
        var op1Kind = instruction.Op1Kind;
        
        bool isVex = instruction.Mnemonic == Mnemonic.Vmovd || instruction.Mnemonic == Mnemonic.Vmovq;
        bool is64 = instruction.Mnemonic == Mnemonic.Vmovq || instruction.Mnemonic == Mnemonic.Movq;

        if (op0Kind == OpKind.Register && op1Kind == OpKind.Register)
        {
            if (instruction.Op0Register.IsVectorRegister() && instruction.Op1Register.IsGPR())
            {
                // VMOVD/Q xmm, r32/r64
                int dstReg = GetVectorRegisterIndex(instruction.Op0Register, out _);
                ulong srcVal = GetRegister(instruction.Op1Register);

                if (!is64) srcVal = (uint)srcVal;

                _context.SetXmmRegister(dstReg, srcVal, 0); // Upper 64-bits of XMM always zeroed
                if (isVex) _context.ClearYmmUpper(dstReg);
            }
            else if (instruction.Op0Register.IsGPR() && instruction.Op1Register.IsVectorRegister())
            {
                // VMOVD/Q r32/r64, xmm
                int srcReg = GetVectorRegisterIndex(instruction.Op1Register, out _);
                _context.GetXmmRegister(srcReg, out ulong lowLow, out _);

                if (!is64) lowLow = (uint)lowLow;
                SetRegister(instruction.Op0Register, lowLow);
            }
            else if (instruction.Op0Register.IsVectorRegister() && instruction.Op1Register.IsVectorRegister())
            {
                // VMOVQ xmm1, xmm2
                int dstReg = GetVectorRegisterIndex(instruction.Op0Register, out _);
                int srcReg = GetVectorRegisterIndex(instruction.Op1Register, out _);
                _context.GetXmmRegister(srcReg, out ulong lowLow, out _);
                
                _context.SetXmmRegister(dstReg, lowLow, 0);
                if (isVex) _context.ClearYmmUpper(dstReg);
            }
            else
            {
                throw new Exception($"Unsupported Vmovd/q register combination");
            }
        }
        else if (op0Kind == OpKind.Register && op1Kind == OpKind.Memory)
        {
            // VMOVD/Q xmm, m32/m64
            int dstReg = GetVectorRegisterIndex(instruction.Op0Register, out _);
            ulong memAddr = GetMemoryAddress(ref instruction);
            ulong val = is64 ? ReadMemory(ref instruction, memAddr) : BinaryPrimitives.ReadUInt32LittleEndian(_memory.GetSpan(TranslateAddress(memAddr), 4));
            
            _context.SetXmmRegister(dstReg, val, 0);
            if (isVex) _context.ClearYmmUpper(dstReg);
        }
        else if (op0Kind == OpKind.Memory && op1Kind == OpKind.Register)
        {
            // VMOVD/Q m32/m64, xmm
            ulong dstAddr = GetMemoryAddress(ref instruction);
            int srcReg = GetVectorRegisterIndex(instruction.Op1Register, out _);
            _context.GetXmmRegister(srcReg, out ulong lowLow, out _);

            if (is64)
                WriteMemory(ref instruction, dstAddr, lowLow);
            else
                BinaryPrimitives.WriteUInt32LittleEndian(_memory.GetSpan(TranslateAddress(dstAddr), 4), (uint)lowLow);
        }
        else
        {
            throw new Exception($"Unsupported Vmovd/q operands: {op0Kind}, {op1Kind}");
        }
    }

    private void HandleVpcmpeqd(ref Instruction instruction)
    {
        var op0Kind = instruction.Op0Kind;
        var op1Kind = instruction.Op1Kind;
        var op2Kind = instruction.Op2Kind;
        bool isVex = instruction.Mnemonic == Mnemonic.Vpcmpeqd;

        if (op0Kind == OpKind.Register && op1Kind == OpKind.Register && op2Kind == OpKind.Register)
        {
            int dstReg = GetVectorRegisterIndex(instruction.Op0Register, out bool dstIsYmm);
            int src1Reg = GetVectorRegisterIndex(instruction.Op1Register, out _);
            int src2Reg = GetVectorRegisterIndex(instruction.Op2Register, out _);

            _context.GetXmmRegister(src1Reg, out ulong lowLow1, out ulong lowHigh1);
            _context.GetXmmRegister(src2Reg, out ulong lowLow2, out ulong lowHigh2);

            uint[] res = new uint[8];
            uint[] s1 = new uint[8];
            uint[] s2 = new uint[8];

            s1[0] = (uint)(lowLow1 & 0xFFFFFFFF);
            s1[1] = (uint)(lowLow1 >> 32);
            s1[2] = (uint)(lowHigh1 & 0xFFFFFFFF);
            s1[3] = (uint)(lowHigh1 >> 32);

            s2[0] = (uint)(lowLow2 & 0xFFFFFFFF);
            s2[1] = (uint)(lowLow2 >> 32);
            s2[2] = (uint)(lowHigh2 & 0xFFFFFFFF);
            s2[3] = (uint)(lowHigh2 >> 32);

            if (dstIsYmm)
            {
                _context.GetYmmUpper(src1Reg, out ulong highLow1, out ulong highHigh1);
                _context.GetYmmUpper(src2Reg, out ulong highLow2, out ulong highHigh2);

                s1[4] = (uint)(highLow1 & 0xFFFFFFFF);
                s1[5] = (uint)(highLow1 >> 32);
                s1[6] = (uint)(highHigh1 & 0xFFFFFFFF);
                s1[7] = (uint)(highHigh1 >> 32);

                s2[4] = (uint)(highLow2 & 0xFFFFFFFF);
                s2[5] = (uint)(highLow2 >> 32);
                s2[6] = (uint)(highHigh2 & 0xFFFFFFFF);
                s2[7] = (uint)(highHigh2 >> 32);
            }

            int count = dstIsYmm ? 8 : 4;
            for (int i = 0; i < count; i++)
            {
                res[i] = (s1[i] == s2[i]) ? 0xFFFFFFFF : 0;
            }

            ulong resLowLow = res[0] | ((ulong)res[1] << 32);
            ulong resLowHigh = res[2] | ((ulong)res[3] << 32);
            _context.SetXmmRegister(dstReg, resLowLow, resLowHigh);

            if (dstIsYmm)
            {
                ulong resHighLow = res[4] | ((ulong)res[5] << 32);
                ulong resHighHigh = res[6] | ((ulong)res[7] << 32);
                _context.SetYmmUpper(dstReg, resHighLow, resHighHigh);
            }
            else if (isVex)
            {
                _context.ClearYmmUpper(dstReg);
            }
        }
        else
        {
            throw new Exception($"Unsupported Vpcmpeqd operands: {op0Kind}, {op1Kind}, {op2Kind}");
        }
    }

    private void HandleVbroadcast(ref Instruction instruction)
    {
        var op0Kind = instruction.Op0Kind;
        var op1Kind = instruction.Op1Kind;

        if (op0Kind == OpKind.Register && (op1Kind == OpKind.Memory || op1Kind == OpKind.Register))
        {
            int dstReg = GetVectorRegisterIndex(instruction.Op0Register, out bool dstIsYmm);
            bool isSingle = instruction.Mnemonic == Mnemonic.Vbroadcastss;
            
            ulong val64;
            if (op1Kind == OpKind.Memory)
            {
                ulong memAddr = GetMemoryAddress(ref instruction);
                if (isSingle)
                {
                    uint val32 = BinaryPrimitives.ReadUInt32LittleEndian(_memory.GetSpan(TranslateAddress(memAddr), 4));
                    val64 = val32 | ((ulong)val32 << 32);
                }
                else
                {
                    val64 = ReadMemory(ref instruction, memAddr);
                }
            }
            else
            {
                int srcReg = GetVectorRegisterIndex(instruction.Op1Register, out _);
                _context.GetXmmRegister(srcReg, out ulong lowLow, out _);
                if (isSingle)
                {
                    uint val32 = (uint)(lowLow & 0xFFFFFFFF);
                    val64 = val32 | ((ulong)val32 << 32);
                }
                else
                {
                    val64 = lowLow;
                }
            }

            _context.SetXmmRegister(dstReg, val64, val64);

            if (dstIsYmm)
            {
                _context.SetYmmUpper(dstReg, val64, val64);
            }
            else
            {
                _context.ClearYmmUpper(dstReg);
            }
        }
        else
        {
            throw new Exception($"Unsupported Vbroadcast operands: {op0Kind}, {op1Kind}");
        }
    }

    private void HandleVpextrq(ref Instruction instruction)
    {
        var op0Kind = instruction.Op0Kind;
        var op1Kind = instruction.Op1Kind;
        var op2Kind = instruction.Op2Kind;

        if (op1Kind == OpKind.Register && (op0Kind == OpKind.Register || op0Kind == OpKind.Memory))
        {
            int srcReg = GetVectorRegisterIndex(instruction.Op1Register, out _);
            _context.GetXmmRegister(srcReg, out ulong lowLow, out ulong lowHigh);

            int index = (int)instruction.Immediate8 & 1; // 0 or 1 for quadwords in XMM
            ulong value = index == 0 ? lowLow : lowHigh;

            if (op0Kind == OpKind.Register)
            {
                SetRegister(instruction.Op0Register, value);
            }
            else
            {
                ulong memAddr = GetMemoryAddress(ref instruction);
                WriteMemory(ref instruction, memAddr, value);
            }
        }
        else
        {
            throw new Exception($"Unsupported Vpextrq operands: {op0Kind}, {op1Kind}, {op2Kind}");
        }
    }

    private int GetVectorRegisterIndex(Register register, out bool isYmm)
    {
        isYmm = false;
        if (register >= Register.XMM0 && register <= Register.XMM31)
            return register - Register.XMM0;
        if (register >= Register.YMM0 && register <= Register.YMM31)
        {
            isYmm = true;
            return register - Register.YMM0;
        }
        throw new InvalidOperationException($"Not a vector register: {register}");
    }


    private void UpdateAddFlags(ulong src0, ulong src1, ulong result, int size)
    {
        ulong mask = size == 1 ? 0xFFUL : (size == 2 ? 0xFFFFUL : (size == 4 ? 0xFFFFFFFFUL : 0xFFFFFFFFFFFFFFFFUL));
        ulong signMask = size == 1 ? 0x80UL : (size == 2 ? 0x8000UL : (size == 4 ? 0x80000000UL : 0x8000000000000000UL));

        ulong tr = result & mask;
        _context.ZeroFlag = (tr == 0);
        _context.SignFlag = ((tr & signMask) != 0);

        ulong s0 = src0 & mask;
        ulong s1 = src1 & mask;
        _context.OverflowFlag = ((~(s0 ^ s1) & (s0 ^ tr)) & signMask) != 0;
        
        if (size == 1) _context.CarryFlag = result > 0xFFUL;
        else if (size == 2) _context.CarryFlag = result > 0xFFFFUL;
        else if (size == 4) _context.CarryFlag = result > 0xFFFFFFFFUL;
        else _context.CarryFlag = result < src0;
    }

    private void UpdateSubFlags(ulong src0, ulong src1, ulong result, int size)
    {
        ulong mask = size == 1 ? 0xFFUL : (size == 2 ? 0xFFFFUL : (size == 4 ? 0xFFFFFFFFUL : 0xFFFFFFFFFFFFFFFFUL));
        ulong signMask = size == 1 ? 0x80UL : (size == 2 ? 0x8000UL : (size == 4 ? 0x80000000UL : 0x8000000000000000UL));

        ulong tr = result & mask;
        _context.ZeroFlag = (tr == 0);
        _context.SignFlag = ((tr & signMask) != 0);

        ulong s0 = src0 & mask;
        ulong s1 = src1 & mask;
        _context.OverflowFlag = (((s0 ^ s1) & (s0 ^ tr)) & signMask) != 0;

        _context.CarryFlag = s0 < s1;
    }

    private void UpdateBitwiseFlags(ulong result, int size)
    {
        ulong mask = size == 1 ? 0xFFUL : (size == 2 ? 0xFFFFUL : (size == 4 ? 0xFFFFFFFFUL : 0xFFFFFFFFFFFFFFFFUL));
        ulong signMask = size == 1 ? 0x80UL : (size == 2 ? 0x8000UL : (size == 4 ? 0x80000000UL : 0x8000000000000000UL));

        ulong tr = result & mask;
        _context.ZeroFlag = (tr == 0);
        _context.SignFlag = ((tr & signMask) != 0);
        _context.OverflowFlag = false;
        _context.CarryFlag = false;
    }
    
    private int GetOpSize(ref Instruction instruction, int opIdx)
    {
        if (opIdx == 0)
        {
            if (instruction.Op0Kind == OpKind.Register) return instruction.Op0Register.GetSize();
            if (instruction.Op0Kind == OpKind.Memory) return instruction.MemorySize.GetSize();
        }
        else if (opIdx == 1)
        {
            if (instruction.Op1Kind == OpKind.Register) return instruction.Op1Register.GetSize();
            if (instruction.Op1Kind == OpKind.Memory) return instruction.MemorySize.GetSize();
        }
        return 8;
    }

    private void HandleAdd(ref Instruction instruction)
    {
        ulong srcValue = 0;
        if (instruction.Op1Kind == OpKind.Register)
        {
            srcValue = GetRegister(instruction.Op1Register);
        }
        else if (IsImmediate(instruction.Op1Kind))
        {
            srcValue = instruction.GetImmediate(1);
        }
        else if (instruction.Op1Kind == OpKind.Memory)
        {
            ulong src1Addr = GetMemoryAddress(ref instruction);
            srcValue = ReadMemory(ref instruction, src1Addr);
        }
        else
        {
            throw new InvalidOpcodeException(_context.Rip, 0);
        }

        ulong dstValue = 0;
        ulong address = 0;
        if (instruction.Op0Kind == OpKind.Register)
        {
            dstValue = GetRegister(instruction.Op0Register);
        }
        else if (instruction.Op0Kind == OpKind.Memory)
        {
            address = GetMemoryAddress(ref instruction);
            if (address == 0 || address == 0x200000000)
            {
                address = _memory.AllocateGpu(0);
            }
            var span = _memory.GetSpan(address, 8);
            dstValue = BinaryPrimitives.ReadUInt64LittleEndian(span);
        }
        else
        {
            throw new InvalidOpcodeException(_context.Rip, 0);
        }

        ulong result = dstValue + srcValue;

        if (instruction.Op0Kind == OpKind.Register)
        {
            SetRegister(instruction.Op0Register, result);
        }
        else if (instruction.Op0Kind == OpKind.Memory)
        {
            var span = _memory.GetSpan(address, 8);
            BinaryPrimitives.WriteUInt64LittleEndian(span, result);
        }
    }

    private void HandleSub(ref Instruction instruction)
    {
        ulong srcValue = 0;
        if (instruction.Op1Kind == OpKind.Register)
        {
            srcValue = GetRegister(instruction.Op1Register);
        }
        else if (IsImmediate(instruction.Op1Kind))
        {
            srcValue = instruction.GetImmediate(1);
        }
        else if (instruction.Op1Kind == OpKind.Memory)
        {
            ulong src1Addr = GetMemoryAddress(ref instruction);
            srcValue = ReadMemory(ref instruction, src1Addr);
        }
        else
        {
            throw new InvalidOpcodeException(_context.Rip, 0);
        }

        ulong dstValue = 0;
        ulong address = 0;
        if (instruction.Op0Kind == OpKind.Register)
        {
            dstValue = GetRegister(instruction.Op0Register);
        }
        else if (instruction.Op0Kind == OpKind.Memory)
        {
            address = GetMemoryAddress(ref instruction);
            if (address == 0 || address == 0x200000000)
            {
                address = _memory.AllocateGpu(0);
            }
            var span = _memory.GetSpan(address, 8);
            dstValue = BinaryPrimitives.ReadUInt64LittleEndian(span);
        }
        else
        {
            throw new InvalidOpcodeException(_context.Rip, 0);
        }

        ulong result = dstValue - srcValue;
        UpdateSubFlags(dstValue, srcValue, result, GetOpSize(ref instruction, 0));

        if (instruction.Op0Kind == OpKind.Register)
        {
            SetRegister(instruction.Op0Register, result);
        }
        else if (instruction.Op0Kind == OpKind.Memory)
        {
            var span = _memory.GetSpan(address, 8);
            BinaryPrimitives.WriteUInt64LittleEndian(span, result);
        }
    }

    private void HandleXor(ref Instruction instruction)
    {
        ulong srcValue = 0;
        if (instruction.Op1Kind == OpKind.Register)
        {
            srcValue = GetRegister(instruction.Op1Register);
        }
        else if (IsImmediate(instruction.Op1Kind))
        {
            srcValue = instruction.GetImmediate(1);
        }
        else if (instruction.Op1Kind == OpKind.Memory)
        {
            ulong src1Addr = GetMemoryAddress(ref instruction);
            srcValue = ReadMemory(ref instruction, src1Addr);
        }
        else
        {
            throw new InvalidOpcodeException(_context.Rip, 0);
        }

        ulong dstValue = 0;
        ulong address = 0;
        if (instruction.Op0Kind == OpKind.Register)
        {
            dstValue = GetRegister(instruction.Op0Register);
        }
        else if (instruction.Op0Kind == OpKind.Memory)
        {
            address = GetMemoryAddress(ref instruction);
            if (address == 0 || address == 0x200000000)
            {
                address = _memory.AllocateGpu(0);
            }
            var span = _memory.GetSpan(address, 8);
            dstValue = BinaryPrimitives.ReadUInt64LittleEndian(span);
        }
        else
        {
            throw new InvalidOpcodeException(_context.Rip, 0);
        }

        ulong result = dstValue ^ srcValue;
        UpdateBitwiseFlags(result, GetOpSize(ref instruction, 0));

        if (instruction.Op0Kind == OpKind.Register)
        {
            SetRegister(instruction.Op0Register, result);
        }
        else if (instruction.Op0Kind == OpKind.Memory)
        {
            var span = _memory.GetSpan(address, 8);
            BinaryPrimitives.WriteUInt64LittleEndian(span, result);
        }
    }

    private void HandleOr(ref Instruction instruction)
    {
        ulong srcValue = 0;
        if (instruction.Op1Kind == OpKind.Register)
        {
            srcValue = GetRegister(instruction.Op1Register);
        }
        else if (IsImmediate(instruction.Op1Kind))
        {
            srcValue = instruction.GetImmediate(1);
        }
        else if (instruction.Op1Kind == OpKind.Memory)
        {
            ulong src1Addr = GetMemoryAddress(ref instruction);
            srcValue = ReadMemory(ref instruction, src1Addr);
        }
        else
        {
            throw new InvalidOpcodeException(_context.Rip, 0);
        }

        ulong dstValue = 0;
        ulong address = 0;
        if (instruction.Op0Kind == OpKind.Register)
        {
            dstValue = GetRegister(instruction.Op0Register);
        }
        else if (instruction.Op0Kind == OpKind.Memory)
        {
            address = GetMemoryAddress(ref instruction);
            if (address == 0 || address == 0x200000000)
            {
                address = _memory.AllocateGpu(0);
            }
            var span = _memory.GetSpan(address, 8);
            dstValue = BinaryPrimitives.ReadUInt64LittleEndian(span);
        }
        else
        {
            throw new InvalidOpcodeException(_context.Rip, 0);
        }

        ulong result = dstValue | srcValue;
        UpdateBitwiseFlags(result, GetOpSize(ref instruction, 0));

        if (instruction.Op0Kind == OpKind.Register)
        {
            SetRegister(instruction.Op0Register, result);
        }
        else if (instruction.Op0Kind == OpKind.Memory)
        {
            var span = _memory.GetSpan(address, 8);
            BinaryPrimitives.WriteUInt64LittleEndian(span, result);
        }
    }

    private void HandleLea(ref Instruction instruction)
    {
        if (instruction.Op0Kind != OpKind.Register) throw new InvalidOpcodeException(_context.Rip, 0);
        ulong address = GetMemoryAddress(ref instruction);
        SetRegister(instruction.Op0Register, address);
    }

    private void HandleRet(ref Instruction instruction)
    {
        const int StackSlotSize = 8;
        ulong rsp = GetRegister(Iced.Intel.Register.RSP);
        var span = _memory.GetSpan(rsp, StackSlotSize);
        _context.Rip = BinaryPrimitives.ReadUInt64LittleEndian(span);
        SetRegister(Iced.Intel.Register.RSP, rsp + StackSlotSize);
    }

    private void HandleCall(ref Instruction instruction)
    {
        ulong nextRip = _context.Rip + (ulong)instruction.Length;
        const int StackSlotSize = 8;
        ulong rsp = GetRegister(Iced.Intel.Register.RSP) - StackSlotSize;
        SetRegister(Iced.Intel.Register.RSP, rsp);
        var span = _memory.GetSpan(rsp, StackSlotSize);
        BinaryPrimitives.WriteUInt64LittleEndian(span, nextRip);
        
        if (instruction.Op0Kind == OpKind.NearBranch64) _context.Rip = instruction.NearBranchTarget;
        else if (instruction.Op0Kind == OpKind.Register) _context.Rip = GetRegister(instruction.Op0Register);
        else if (instruction.Op0Kind == OpKind.Memory) _context.Rip = BinaryPrimitives.ReadUInt64LittleEndian(_memory.GetSpan(GetMemoryAddress(ref instruction), 8));
        else throw new InvalidOpcodeException(_context.Rip, 0);
    }

    private void HandleAnd(ref Instruction instruction)
    {
        ulong srcValue = 0;
        if (instruction.Op1Kind == OpKind.Register) srcValue = GetRegister(instruction.Op1Register);
        else if (IsImmediate(instruction.Op1Kind)) srcValue = instruction.GetImmediate(1);
        else if (instruction.Op1Kind == OpKind.Memory) srcValue = BinaryPrimitives.ReadUInt64LittleEndian(_memory.GetSpan(GetMemoryAddress(ref instruction), 8));
        else throw new InvalidOpcodeException(_context.Rip, 0);

        ulong dstValue = 0;
        ulong address = 0;
        if (instruction.Op0Kind == OpKind.Register) dstValue = GetRegister(instruction.Op0Register);
        else if (instruction.Op0Kind == OpKind.Memory)
        {
            address = GetMemoryAddress(ref instruction);
            if (address == 0 || address == 0x200000000) address = _memory.AllocateGpu(0);
            dstValue = BinaryPrimitives.ReadUInt64LittleEndian(_memory.GetSpan(address, 8));
        }
        else throw new InvalidOpcodeException(_context.Rip, 0);

        ulong result = dstValue & srcValue;
        UpdateBitwiseFlags(result, GetOpSize(ref instruction, 0));

        if (instruction.Op0Kind == OpKind.Register) SetRegister(instruction.Op0Register, result);
        else if (instruction.Op0Kind == OpKind.Memory) BinaryPrimitives.WriteUInt64LittleEndian(_memory.GetSpan(address, 8), result);
    }

    private void HandleTest(ref Instruction instruction)
    {
        ulong src0 = 0;
        if (instruction.Op0Kind == OpKind.Register) src0 = GetRegister(instruction.Op0Register);
        else if (instruction.Op0Kind == OpKind.Memory) src0 = BinaryPrimitives.ReadUInt64LittleEndian(_memory.GetSpan(GetMemoryAddress(ref instruction), 8));
        else throw new InvalidOpcodeException(_context.Rip, 0);

        ulong src1 = 0;
        if (instruction.Op1Kind == OpKind.Register) src1 = GetRegister(instruction.Op1Register);
        else if (IsImmediate(instruction.Op1Kind)) src1 = instruction.GetImmediate(1);
        else if (instruction.Op1Kind == OpKind.Memory) src1 = BinaryPrimitives.ReadUInt64LittleEndian(_memory.GetSpan(GetMemoryAddress(ref instruction), 8));
        else throw new InvalidOpcodeException(_context.Rip, 0);

        ulong result = src0 & src1;
        UpdateBitwiseFlags(result, GetOpSize(ref instruction, 0));
    }

    private void HandleShl(ref Instruction instruction)
    {
        ulong dstValue = 0;
        ulong address = 0;
        if (instruction.Op0Kind == OpKind.Register) dstValue = GetRegister(instruction.Op0Register);
        else if (instruction.Op0Kind == OpKind.Memory)
        {
            address = GetMemoryAddress(ref instruction);
            dstValue = ReadMemory(ref instruction, address);
        }
        else throw new InvalidOpcodeException(_context.Rip, 0);

        ulong count = 0;
        if (instruction.Op1Kind == OpKind.Register) count = GetRegister(instruction.Op1Register) & 0x3F;
        else if (instruction.Op1Kind == OpKind.Immediate8) count = (ulong)(instruction.Immediate8 & 0x3F);
        else throw new InvalidOpcodeException(_context.Rip, 0);

        if (count > 0)
        {
            _context.CarryFlag = ((dstValue >> (64 - (int)count)) & 1) != 0;
            dstValue <<= (int)count;
            _context.ZeroFlag = (dstValue == 0);
            _context.SignFlag = ((long)dstValue < 0);
        }

        if (instruction.Op0Kind == OpKind.Register) SetRegister(instruction.Op0Register, dstValue);
        else if (instruction.Op0Kind == OpKind.Memory) WriteMemory(ref instruction, address, dstValue);
    }

    private void HandleShr(ref Instruction instruction)
    {
        ulong dstValue = 0;
        ulong address = 0;
        if (instruction.Op0Kind == OpKind.Register) dstValue = GetRegister(instruction.Op0Register);
        else if (instruction.Op0Kind == OpKind.Memory)
        {
            address = GetMemoryAddress(ref instruction);
            dstValue = ReadMemory(ref instruction, address);
        }
        else throw new InvalidOpcodeException(_context.Rip, 0);

        ulong count = 0;
        if (instruction.Op1Kind == OpKind.Register) count = GetRegister(instruction.Op1Register) & 0x3F;
        else if (instruction.Op1Kind == OpKind.Immediate8) count = (ulong)(instruction.Immediate8 & 0x3F);
        else throw new InvalidOpcodeException(_context.Rip, 0);

        if (count > 0)
        {
            _context.CarryFlag = ((dstValue >> ((int)count - 1)) & 1) != 0;
            dstValue >>= (int)count;
            _context.ZeroFlag = (dstValue == 0);
            _context.SignFlag = ((long)dstValue < 0);
        }

        if (instruction.Op0Kind == OpKind.Register) SetRegister(instruction.Op0Register, dstValue);
        else if (instruction.Op0Kind == OpKind.Memory) WriteMemory(ref instruction, address, dstValue);
    }

    private void HandleSar(ref Instruction instruction)
    {
        ulong dstValue = 0;
        ulong address = 0;
        if (instruction.Op0Kind == OpKind.Register) dstValue = GetRegister(instruction.Op0Register);
        else if (instruction.Op0Kind == OpKind.Memory)
        {
            address = GetMemoryAddress(ref instruction);
            dstValue = ReadMemory(ref instruction, address);
        }
        else throw new InvalidOpcodeException(_context.Rip, 0);

        ulong count = 0;
        if (instruction.Op1Kind == OpKind.Register) count = GetRegister(instruction.Op1Register) & 0x3F;
        else if (instruction.Op1Kind == OpKind.Immediate8) count = (ulong)(instruction.Immediate8 & 0x3F);
        else throw new InvalidOpcodeException(_context.Rip, 0);

        if (count > 0)
        {
            long signedDst = (long)dstValue;
            _context.CarryFlag = ((signedDst >> ((int)count - 1)) & 1) != 0;
            signedDst >>= (int)count;
            dstValue = (ulong)signedDst;
            _context.ZeroFlag = (dstValue == 0);
            _context.SignFlag = ((long)dstValue < 0);
        }

        if (instruction.Op0Kind == OpKind.Register) SetRegister(instruction.Op0Register, dstValue);
        else if (instruction.Op0Kind == OpKind.Memory) WriteMemory(ref instruction, address, dstValue);
    }

    private void HandleMovzx(ref Instruction instruction)
    {
        ulong srcValue = 0;
        if (instruction.Op1Kind == OpKind.Register)
        {
            srcValue = GetRegister(instruction.Op1Register);
            if (instruction.Op1Register >= Register.AL && instruction.Op1Register <= Register.R15L) srcValue &= 0xFF;
            else if (instruction.Op1Register >= Register.AX && instruction.Op1Register <= Register.R15W) srcValue &= 0xFFFF;
            else if (instruction.Op1Register >= Register.EAX && instruction.Op1Register <= Register.R15D) srcValue &= 0xFFFFFFFF;
        }
        else if (instruction.Op1Kind == OpKind.Memory)
        {
            ulong address = GetMemoryAddress(ref instruction);
            if (instruction.MemorySize == MemorySize.UInt8 || instruction.MemorySize == MemorySize.Int8) srcValue = _memory.GetSpan(address, 1)[0];
            else if (instruction.MemorySize == MemorySize.UInt16 || instruction.MemorySize == MemorySize.Int16) srcValue = BinaryPrimitives.ReadUInt16LittleEndian(_memory.GetSpan(address, 2));
            else if (instruction.MemorySize == MemorySize.UInt32 || instruction.MemorySize == MemorySize.Int32) srcValue = BinaryPrimitives.ReadUInt32LittleEndian(_memory.GetSpan(address, 4));
            else srcValue = BinaryPrimitives.ReadUInt64LittleEndian(_memory.GetSpan(address, 8));
        }
        else throw new InvalidOpcodeException(_context.Rip, 0);

        SetRegister(instruction.Op0Register, srcValue);
    }

    private void HandleMovsxd(ref Instruction instruction)
    {
        ulong srcValue = 0;
        if (instruction.Op1Kind == OpKind.Register)
        {
            srcValue = GetRegister(instruction.Op1Register);
            if (instruction.Op1Register >= Register.EAX && instruction.Op1Register <= Register.R15D) srcValue = (ulong)(int)(uint)srcValue;
            else throw new InvalidOpcodeException(_context.Rip, 0);
        }
        else if (instruction.Op1Kind == OpKind.Memory)
        {
            ulong address = GetMemoryAddress(ref instruction);
            srcValue = (ulong)(int)(uint)ReadMemory(ref instruction, address);
        }
        else throw new InvalidOpcodeException(_context.Rip, 0);

        SetRegister(instruction.Op0Register, srcValue);
    }

    private void HandleImul(ref Instruction instruction)
    {
        if (instruction.OpCount == 1)
        {
            ulong srcValue = 0;
            if (instruction.Op0Kind == OpKind.Register) srcValue = GetRegister(instruction.Op0Register);
            else if (instruction.Op0Kind == OpKind.Memory) srcValue = ReadMemory(ref instruction, GetMemoryAddress(ref instruction));
            
            long result = (long)_context[CpuRegister.Rax] * (long)srcValue;
            _context[CpuRegister.Rax] = (ulong)result;
            _context[CpuRegister.Rdx] = (result < 0) ? ~(ulong)0 : 0; 
        }
        else if (instruction.OpCount == 2)
        {
            ulong srcValue = 0;
            if (instruction.Op1Kind == OpKind.Register) srcValue = GetRegister(instruction.Op1Register);
            else if (instruction.Op1Kind == OpKind.Memory) srcValue = ReadMemory(ref instruction, GetMemoryAddress(ref instruction));
            else if (IsImmediate(instruction.Op1Kind)) srcValue = instruction.GetImmediate(1);
            
            ulong dstValue = GetRegister(instruction.Op0Register);
            long result = (long)dstValue * (long)srcValue;
            SetRegister(instruction.Op0Register, (ulong)result);
        }
        else if (instruction.OpCount == 3)
        {
            ulong srcValue = 0;
            if (instruction.Op1Kind == OpKind.Register) srcValue = GetRegister(instruction.Op1Register);
            else if (instruction.Op1Kind == OpKind.Memory) srcValue = ReadMemory(ref instruction, GetMemoryAddress(ref instruction));

            ulong imm = instruction.GetImmediate(2);
            long result = (long)srcValue * (long)imm;
            SetRegister(instruction.Op0Register, (ulong)result);
        }
        else throw new InvalidOpcodeException(_context.Rip, 0);
    }

    private void HandleLzcnt(ref Instruction instruction)
    {
        ulong src;
        if (instruction.Op1Kind == OpKind.Register)
        {
            src = GetRegister(instruction.Op1Register);
        }
        else if (instruction.Op1Kind == OpKind.Memory)
        {
            src = ReadMemory(ref instruction, GetMemoryAddress(ref instruction));
        }
        else
        {
            throw new Exception($"Unsupported LZCNT operand 1 kind: {instruction.Op1Kind}");
        }

        int size = instruction.Op0Register.GetSize();
        ulong result;

        if (size == 2)
        {
            result = (ulong)System.Numerics.BitOperations.LeadingZeroCount((uint)(src & 0xFFFF)) - 16;
        }
        else if (size == 4)
        {
            result = (ulong)System.Numerics.BitOperations.LeadingZeroCount((uint)src);
        }
        else if (size == 8)
        {
            result = (ulong)System.Numerics.BitOperations.LeadingZeroCount((ulong)src);
        }
        else
        {
            throw new Exception($"Unsupported LZCNT size: {size}");
        }

        SetRegister(instruction.Op0Register, result);

        // Update flags
        // CF = 1 if SRC == 0, else 0
        // ZF = 1 if result == 0, else 0
        // SF, OF, AF, PF are undefined. We just clear them.
        _context.CarryFlag = (src == 0);
        _context.ZeroFlag = (result == 0);
        _context.SignFlag = false;
        _context.OverflowFlag = false;
    }

    private void HandleMul(ref Instruction instruction)
    {
        int size = instruction.Op0Register.GetSize();
        if (instruction.Op0Kind == OpKind.Memory)
        {
            size = instruction.MemorySize.GetSize();
        }

        ulong operand;
        if (instruction.Op0Kind == OpKind.Register)
        {
            operand = GetRegister(instruction.Op0Register);
        }
        else if (instruction.Op0Kind == OpKind.Memory)
        {
            operand = ReadMemory(ref instruction, GetMemoryAddress(ref instruction));
        }
        else
        {
            throw new Exception($"Unsupported MUL operand kind: {instruction.Op0Kind}");
        }

        if (size == 1) // AL * r/m8
        {
            ushort result = (ushort)((GetRegister(Iced.Intel.Register.AL) & 0xFF) * (operand & 0xFF));
            SetRegister(Iced.Intel.Register.AX, result);
        }
        else if (size == 2) // AX * r/m16 -> DX:AX
        {
            uint result = (uint)((GetRegister(Iced.Intel.Register.AX) & 0xFFFF) * (operand & 0xFFFF));
            SetRegister(Iced.Intel.Register.AX, result & 0xFFFF);
            SetRegister(Iced.Intel.Register.DX, result >> 16);
        }
        else if (size == 4) // EAX * r/m32 -> EDX:EAX
        {
            ulong result = (ulong)(GetRegister(Iced.Intel.Register.EAX) & 0xFFFFFFFF) * (ulong)(operand & 0xFFFFFFFF);
            SetRegister(Iced.Intel.Register.RAX, result & 0xFFFFFFFF); // zero extends to RAX
            SetRegister(Iced.Intel.Register.RDX, result >> 32);        // zero extends to RDX
        }
        else if (size == 8) // RAX * r/m64 -> RDX:RAX
        {
            ulong rax = GetRegister(Iced.Intel.Register.RAX);
            UInt128 result = (UInt128)rax * operand;
            SetRegister(Iced.Intel.Register.RAX, (ulong)result);
            SetRegister(Iced.Intel.Register.RDX, (ulong)(result >> 64));
        }
        else
        {
            throw new Exception($"Unsupported MUL size: {size}");
        }
    }

    private void HandleDiv(ref Instruction instruction)
    {
        ulong divisor;
        if (instruction.Op0Kind == OpKind.Register)
            divisor = GetRegister(instruction.Op0Register);
        else if (instruction.Op0Kind == OpKind.Memory)
            divisor = ReadMemory(ref instruction, GetMemoryAddress(ref instruction));
        else
            throw new InvalidOpcodeException(_context.Rip, 0);

        if (divisor == 0)
            throw new DivideByZeroException($"Division by zero at RIP 0x{_context.Rip:X16}");

        int size = instruction.Op0Kind == OpKind.Register 
            ? instruction.Op0Register.GetSize() 
            : GetOpSize(ref instruction, 0);

        if (size == 4)
        {
            ulong dividend = ((ulong)(uint)GetRegister(Iced.Intel.Register.EDX) << 32) | (uint)GetRegister(Iced.Intel.Register.EAX);
            uint div = (uint)divisor;
            uint quotient = (uint)(dividend / div);
            uint remainder = (uint)(dividend % div);
            SetRegister(Iced.Intel.Register.RAX, quotient); // SetRegister to RAX zero-extends the 32-bit value in the emulation context
            SetRegister(Iced.Intel.Register.RDX, remainder);
        }
        else if (size == 8)
        {
            UInt128 dividend = new UInt128(GetRegister(Iced.Intel.Register.RDX), GetRegister(Iced.Intel.Register.RAX));
            ulong div = divisor;
            ulong quotient = (ulong)(dividend / div);
            ulong remainder = (ulong)(dividend % div);
            SetRegister(Iced.Intel.Register.RAX, quotient);
            SetRegister(Iced.Intel.Register.RDX, remainder);
        }
        else if (size == 2)
        {
            uint dividend = ((uint)(ushort)GetRegister(Iced.Intel.Register.DX) << 16) | (ushort)GetRegister(Iced.Intel.Register.AX);
            ushort div = (ushort)divisor;
            ushort quotient = (ushort)(dividend / div);
            ushort remainder = (ushort)(dividend % div);
            SetRegister(Iced.Intel.Register.AX, quotient);
            SetRegister(Iced.Intel.Register.DX, remainder);
        }
        else if (size == 1)
        {
            ushort dividend = (ushort)GetRegister(Iced.Intel.Register.AX);
            byte div = (byte)divisor;
            byte quotient = (byte)(dividend / div);
            byte remainder = (byte)(dividend % div);
            SetRegister(Iced.Intel.Register.AL, quotient);
            SetRegister(Iced.Intel.Register.AH, remainder);
        }
        else
        {
            throw new InvalidOpcodeException(_context.Rip, 0);
        }
    }

    private void HandleInc(ref Instruction instruction)
    {
        ulong dstValue = 0;
        ulong address = 0;
        if (instruction.Op0Kind == OpKind.Register) dstValue = GetRegister(instruction.Op0Register);
        else if (instruction.Op0Kind == OpKind.Memory)
        {
            address = GetMemoryAddress(ref instruction);
            dstValue = ReadMemory(ref instruction, address);
        }

        ulong result = dstValue + 1;
        UpdateAddFlags(dstValue, 1, result, GetOpSize(ref instruction, 0));

        if (instruction.Op0Kind == OpKind.Register) SetRegister(instruction.Op0Register, result);
        else if (instruction.Op0Kind == OpKind.Memory) WriteMemory(ref instruction, address, result);
    }

    private void HandleDec(ref Instruction instruction)
    {
        ulong dstValue = 0;
        ulong address = 0;
        if (instruction.Op0Kind == OpKind.Register) dstValue = GetRegister(instruction.Op0Register);
        else if (instruction.Op0Kind == OpKind.Memory)
        {
            address = GetMemoryAddress(ref instruction);
            dstValue = ReadMemory(ref instruction, address);
        }

        ulong result = dstValue - 1;
        UpdateSubFlags(dstValue, 1, result, GetOpSize(ref instruction, 0));

        if (instruction.Op0Kind == OpKind.Register) SetRegister(instruction.Op0Register, result);
        else if (instruction.Op0Kind == OpKind.Memory) WriteMemory(ref instruction, address, result);
    }

    private void HandleNeg(ref Instruction instruction)
    {
        ulong dstValue = 0;
        ulong address = 0;
        if (instruction.Op0Kind == OpKind.Register) dstValue = GetRegister(instruction.Op0Register);
        else if (instruction.Op0Kind == OpKind.Memory)
        {
            address = GetMemoryAddress(ref instruction);
            dstValue = ReadMemory(ref instruction, address);
        }

        ulong result = (ulong)(-(long)dstValue);
        _context.ZeroFlag = (result == 0);
        _context.SignFlag = ((long)result < 0);
        _context.CarryFlag = (dstValue != 0);

        if (instruction.Op0Kind == OpKind.Register) SetRegister(instruction.Op0Register, result);
        else if (instruction.Op0Kind == OpKind.Memory) WriteMemory(ref instruction, address, result);
    }

    private void HandleNot(ref Instruction instruction)
    {
        ulong dstValue = 0;
        ulong address = 0;
        if (instruction.Op0Kind == OpKind.Register) dstValue = GetRegister(instruction.Op0Register);
        else if (instruction.Op0Kind == OpKind.Memory)
        {
            address = GetMemoryAddress(ref instruction);
            dstValue = ReadMemory(ref instruction, address);
        }

        ulong result = ~dstValue;

        if (instruction.Op0Kind == OpKind.Register) SetRegister(instruction.Op0Register, result);
        else if (instruction.Op0Kind == OpKind.Memory) WriteMemory(ref instruction, address, result);
    }

    private void HandleCdqe(ref Instruction instruction)
    {
        ulong eax = _context[CpuRegister.Rax] & 0xFFFFFFFF;
        _context[CpuRegister.Rax] = (ulong)(long)(int)eax;
    }


    /// <summary>
    /// Handles a Push instruction by decrementing RSP and writing the source value to the stack.
    /// </summary>
    private void HandlePush(ref Instruction instruction)
    {
        ulong value;

        if (instruction.Op0Kind == OpKind.Register)
        {
            value = GetRegister(instruction.Op0Register);
        }
        else if (IsImmediate(instruction.Op0Kind))
        {
            value = instruction.GetImmediate(0);
        }
        else
        {
            throw new InvalidOpcodeException(_context.Rip, 0);
        }

        // x86-64 push: RSP -= 8, then write value at [RSP]
        const int StackSlotSize = 8;
        ulong rsp = GetRegister(Iced.Intel.Register.RSP) - StackSlotSize;
        SetRegister(Iced.Intel.Register.RSP, rsp);

        var span = _memory.GetSpan(rsp, StackSlotSize);
        BinaryPrimitives.WriteUInt64LittleEndian(span, value);
    }

    /// <summary>
    /// Handles a Pop instruction by reading the value at [RSP] into the destination register
    /// and incrementing RSP.
    /// </summary>
    private void HandlePop(ref Instruction instruction)
    {
        if (instruction.Op0Kind != OpKind.Register)
        {
            throw new InvalidOpcodeException(_context.Rip, 0);
        }

        const int StackSlotSize = 8;
        ulong rsp = GetRegister(Iced.Intel.Register.RSP);

        var span = _memory.GetSpan(rsp, StackSlotSize);
        ulong value = BinaryPrimitives.ReadUInt64LittleEndian(span);

        SetRegister(instruction.Op0Register, value);
        SetRegister(Iced.Intel.Register.RSP, rsp + StackSlotSize);
    }

    /// <summary>
    /// Handles a Cmp instruction by performing a virtual subtraction and updating CPU flags
    /// without storing the result.
    /// </summary>
    private void HandleCmp(ref Instruction instruction)
    {
        ulong src0;
        ulong src1;

        // Resolve operand 0 (left-hand side)
        if (instruction.Op0Kind == OpKind.Register)
        {
            src0 = GetRegister(instruction.Op0Register);
        }
        else if (instruction.Op0Kind == OpKind.Memory)
        {
            ulong src0Addr = GetMemoryAddress(ref instruction);
            src0 = ReadMemory(ref instruction, src0Addr);
        }
        else
        {
            throw new InvalidOpcodeException(_context.Rip, 0);
        }

        // Resolve operand 1 (right-hand side)
        if (instruction.Op1Kind == OpKind.Register)
        {
            src1 = GetRegister(instruction.Op1Register);
        }
        else if (IsImmediate(instruction.Op1Kind))
        {
            src1 = instruction.GetImmediate(1);
        }
        else if (instruction.Op1Kind == OpKind.Memory)
        {
            ulong src1Addr = GetMemoryAddress(ref instruction);
            src1 = ReadMemory(ref instruction, src1Addr);
        }
        else
        {
            throw new InvalidOpcodeException(_context.Rip, 0);
        }

        ulong result = src0 - src1;
        UpdateFlags(src0, src1, result, GetOpSize(ref instruction, 0));
    }

    /// <summary>
    /// Updates ZeroFlag, SignFlag, and OverflowFlag based on the result of a subtraction (src0 - src1).
    /// Overflow is detected using the standard signed-overflow rule for subtraction.
    /// </summary>

    private void HandleShlx(ref Instruction instruction)
    {
        ulong srcValue = 0;
        if (instruction.Op1Kind == OpKind.Register) srcValue = GetRegister(instruction.Op1Register);
        else if (instruction.Op1Kind == OpKind.Memory) srcValue = ReadMemory(ref instruction, GetMemoryAddress(ref instruction));

        ulong countValue = 0;
        if (instruction.Op2Kind == OpKind.Register) countValue = GetRegister(instruction.Op2Register);

        int size = GetOpSize(ref instruction, 0);
        int shiftMask = size == 8 ? 0x3F : 0x1F;
        int shiftCount = (int)(countValue & (uint)shiftMask);
        
        ulong result = 0;
        if (size == 4)
        {
            result = (uint)srcValue << shiftCount;
        }
        else if (size == 8)
        {
            result = srcValue << shiftCount;
        }
        else
        {
            throw new InvalidOpcodeException(_context.Rip, 0);
        }

        SetRegister(instruction.Op0Register, result);
    }

    private void HandleShrx(ref Instruction instruction)
    {
        ulong srcValue = 0;
        if (instruction.Op1Kind == OpKind.Register) srcValue = GetRegister(instruction.Op1Register);
        else if (instruction.Op1Kind == OpKind.Memory) srcValue = ReadMemory(ref instruction, GetMemoryAddress(ref instruction));

        ulong countValue = 0;
        if (instruction.Op2Kind == OpKind.Register) countValue = GetRegister(instruction.Op2Register);

        int size = GetOpSize(ref instruction, 0);
        int shiftMask = size == 8 ? 0x3F : 0x1F;
        int shiftCount = (int)(countValue & (uint)shiftMask);
        
        ulong result = 0;
        if (size == 4)
        {
            result = (uint)srcValue >> shiftCount;
        }
        else if (size == 8)
        {
            result = srcValue >> shiftCount;
        }
        else if (size == 2)
        {
            result = (ulong)((ushort)srcValue >> shiftCount);
        }
        else
        {
            result = (ulong)((byte)srcValue >> shiftCount);
        }

        SetRegister(instruction.Op0Register, result);
    }

    private void HandleBextr(ref Instruction instruction)
    {
        ulong srcValue = 0;
        if (instruction.Op1Kind == OpKind.Register) srcValue = GetRegister(instruction.Op1Register);
        else if (instruction.Op1Kind == OpKind.Memory) srcValue = ReadMemory(ref instruction, GetMemoryAddress(ref instruction));

        ulong control = 0;
        if (instruction.Op2Kind == OpKind.Register) control = GetRegister(instruction.Op2Register);
        else if (IsImmediate(instruction.Op2Kind)) control = instruction.GetImmediate(2);
        
        int start = (int)(control & 0xFF);
        int length = (int)((control >> 8) & 0xFF);
        
        int opSize = GetOpSize(ref instruction, 0);
        int maxBits = opSize * 8;
        
        ulong result = 0;
        if (start < maxBits)
        {
            if (length > maxBits - start) length = maxBits - start;
            if (length > 0)
            {
                ulong mask = (length == 64) ? ulong.MaxValue : ((1UL << length) - 1);
                result = (srcValue >> start) & mask;
            }
        }
        
        UpdateBitwiseFlags(result, opSize);
        SetRegister(instruction.Op0Register, result);
    }

    private void UpdateFlags(ulong src0, ulong src1, ulong result, int size)
    {
        UpdateSubFlags(src0, src1, result, size);
    }

    /// <summary>
    /// Evaluates a conditional jump. If the condition is met, sets RIP to the branch target
    /// and returns true (caller should skip the normal RIP advance). Otherwise returns false.
    /// </summary>


    private void HandleSetcc(ref Instruction instruction, bool conditionMet)
    {
        ulong value = conditionMet ? 1ul : 0ul;
        
        if (instruction.Op0Kind == OpKind.Register)
        {
            SetRegister(instruction.Op0Register, value);
        }
        else if (instruction.Op0Kind == OpKind.Memory)
        {
            ulong address = GetMemoryAddress(ref instruction);
            WriteMemory(ref instruction, address, value);
        }
    }

    private void HandleConditionalMove(ref Instruction instruction, bool conditionMet)
    {
        if (conditionMet)
        {
            ulong srcValue = 0;
            if (instruction.Op1Kind == OpKind.Register)
            {
                srcValue = GetRegister(instruction.Op1Register);
            }
            else if (instruction.Op1Kind == OpKind.Memory)
            {
                ulong src1Addr = GetMemoryAddress(ref instruction);
                srcValue = ReadMemory(ref instruction, src1Addr);
            }

            if (instruction.Op0Kind == OpKind.Register)
            {
                SetRegister(instruction.Op0Register, srcValue);
            }
            else if (instruction.Op0Kind == OpKind.Memory)
            {
                ulong address = GetMemoryAddress(ref instruction);
                WriteMemory(ref instruction, address, srcValue);
            }
        }
    }

    private bool HandleConditionalJump(ref Instruction instruction, bool conditionMet)
    {
        if (conditionMet)
        {
            _context.Rip = instruction.NearBranchTarget;
            return true;
        }

        return false;
    }

    private void HandleInt3(ref Instruction instruction)
    {
        ulong rip = _context.Rip;
        
        string? symbolName = null;
        if (SelfImportStubs != null && SelfImportStubs.TryGetValue(rip, out var nid))
        {
            symbolName = nid;
        }
        else if (DynamicLinker != null)
        {
            DynamicLinker.TryGetSymbolNameByAddress(rip, out symbolName);
        }

        if (symbolName != null && ModuleManager != null)
        {
            try
            {
                if (ModuleManager.TryDispatch(symbolName, _context, out _))
                {
                    // Simulate x86-64 RET
                    ulong rsp = GetRegister(Iced.Intel.Register.RSP);
                    ulong returnAddress = System.Buffers.Binary.BinaryPrimitives.ReadUInt64LittleEndian(_memory.GetSpan(rsp, 8));
                    _context.Rip = returnAddress;
                    SetRegister(Iced.Intel.Register.RSP, rsp + 8);
                    return;
                }
            }
            catch (NotImplementedException ex)
            {
                throw new Exception($"HLE Method for '{symbolName}' is not implemented.", ex);
            }
        }
        
        throw new Exception($"Unmapped or unhandled HLE stub (INT 3 breakpoint) hit at RIP 0x{rip:X16}. Symbol: {symbolName ?? "Unknown"}");
    }

    private ulong TranslateAddress(ulong address)
    {
        if (address == 0) return _memory.AllocateGpu(0); // Legacy catch for null writes
        
        // Crazii_demo.elf and other simple homebrew assume the GPU framebuffer is hardcoded at 0x200000000.
        // We translate any access in this 256MB range to our dynamic GPU allocation pool.
        if (address >= 0x200000000 && address < 0x210000000)
        {
            ulong baseGpu = _memory.AllocateGpu(0); 
            ulong offset = address - 0x200000000;
            return baseGpu + offset;
        }

        return address;
    }

    private ulong ReadMemory(ref Instruction instruction, ulong address)
    {
        address = TranslateAddress(address);
        
        switch (instruction.MemorySize)
        {
            case MemorySize.UInt8:
            case MemorySize.Int8:
                return _memory.GetSpan(address, 1)[0];
            case MemorySize.UInt16:
            case MemorySize.Int16:
                return BinaryPrimitives.ReadUInt16LittleEndian(_memory.GetSpan(address, 2));
            case MemorySize.UInt32:
            case MemorySize.Int32:
                return BinaryPrimitives.ReadUInt32LittleEndian(_memory.GetSpan(address, 4));
            case MemorySize.UInt64:
            case MemorySize.Int64:
            default:
                // Fallback to register size if MemorySize is Unknown
                if (instruction.Op0Kind == OpKind.Register && instruction.Op0Register.GetSize() == 4)
                    return BinaryPrimitives.ReadUInt32LittleEndian(_memory.GetSpan(address, 4));
                if (instruction.Op1Kind == OpKind.Register && instruction.Op1Register.GetSize() == 4)
                    return BinaryPrimitives.ReadUInt32LittleEndian(_memory.GetSpan(address, 4));
                return BinaryPrimitives.ReadUInt64LittleEndian(_memory.GetSpan(address, 8));
        }
    }

    private void WriteMemory(ref Instruction instruction, ulong address, ulong value)
    {
        address = TranslateAddress(address);

        switch (instruction.MemorySize)
        {
            case MemorySize.UInt8:
            case MemorySize.Int8:
                _memory.GetSpan(address, 1)[0] = (byte)value;
                break;
            case MemorySize.UInt16:
            case MemorySize.Int16:
                BinaryPrimitives.WriteUInt16LittleEndian(_memory.GetSpan(address, 2), (ushort)value);
                break;
            case MemorySize.UInt32:
            case MemorySize.Int32:
                BinaryPrimitives.WriteUInt32LittleEndian(_memory.GetSpan(address, 4), (uint)value);
                break;
            case MemorySize.UInt64:
            case MemorySize.Int64:
            default:
                if (instruction.Op0Kind == OpKind.Register && instruction.Op0Register.GetSize() == 4)
                    BinaryPrimitives.WriteUInt32LittleEndian(_memory.GetSpan(address, 4), (uint)value);
                else if (instruction.Op1Kind == OpKind.Register && instruction.Op1Register.GetSize() == 4)
                    BinaryPrimitives.WriteUInt32LittleEndian(_memory.GetSpan(address, 4), (uint)value);
                else
                    BinaryPrimitives.WriteUInt64LittleEndian(_memory.GetSpan(address, 8), value);
                break;
        }
    }

    private ulong GetMemoryAddress(ref Instruction instruction)
    {
        if (instruction.IsIPRelativeMemoryOperand)
        {
            return instruction.IPRelativeMemoryAddress;
        }

        ulong address = 0;
        if (instruction.MemorySegment == Register.FS)
        {
            address += _context.FsBase;
            Console.WriteLine($"[FS DEBUG] Instruction: {instruction}, FsBase: {_context.FsBase:X16}, address so far: {address:X16}");
        }
        else if (instruction.MemorySegment == Register.GS)
        {
            address += _context.GsBase;
        }

        if (instruction.MemoryBase != Register.None)
        {
            if (instruction.MemoryBase == Register.RIP || instruction.MemoryBase == Register.EIP)
            {
                address += _context.Rip;
            }
            else
            {
                address += GetRegister(instruction.MemoryBase);
            }
        }
        if (instruction.MemoryIndex != Register.None)
        {
            address += GetRegister(instruction.MemoryIndex) * (ulong)instruction.MemoryIndexScale;
        }
        address += instruction.MemoryDisplacement64;
        return address;
    }

    private ulong GetRegister(Register reg)
    {
        ulong val = MapRegister(reg) switch
        {
            CpuRegister.Rax => _context[CpuRegister.Rax],
            CpuRegister.Rbx => _context[CpuRegister.Rbx],
            CpuRegister.Rcx => _context[CpuRegister.Rcx],
            CpuRegister.Rdx => _context[CpuRegister.Rdx],
            CpuRegister.Rsi => _context[CpuRegister.Rsi],
            CpuRegister.Rdi => _context[CpuRegister.Rdi],
            CpuRegister.Rbp => _context[CpuRegister.Rbp],
            CpuRegister.Rsp => _context[CpuRegister.Rsp],
            CpuRegister.R8 => _context[CpuRegister.R8],
            CpuRegister.R9 => _context[CpuRegister.R9],
            CpuRegister.R10 => _context[CpuRegister.R10],
            CpuRegister.R11 => _context[CpuRegister.R11],
            CpuRegister.R12 => _context[CpuRegister.R12],
            CpuRegister.R13 => _context[CpuRegister.R13],
            CpuRegister.R14 => _context[CpuRegister.R14],
            CpuRegister.R15 => _context[CpuRegister.R15],
            _ => throw new NotImplementedException($"Register {reg} not implemented in Context.")
        };

        if (reg == Register.AH || reg == Register.BH || reg == Register.CH || reg == Register.DH)
            return (val >> 8) & 0xFF;

        int size = reg.GetSize();
        if (size == 1) return val & 0xFF;
        if (size == 2) return val & 0xFFFF;
        if (size == 4) return val & 0xFFFFFFFF;
        return val;
    }

    private void SetRegister(Register reg, ulong value)
    {
        var mapped = MapRegister(reg);
        
        ulong currentValue = mapped switch {
            CpuRegister.Rax => _context[CpuRegister.Rax],
            CpuRegister.Rbx => _context[CpuRegister.Rbx],
            CpuRegister.Rcx => _context[CpuRegister.Rcx],
            CpuRegister.Rdx => _context[CpuRegister.Rdx],
            CpuRegister.Rsi => _context[CpuRegister.Rsi],
            CpuRegister.Rdi => _context[CpuRegister.Rdi],
            CpuRegister.Rbp => _context[CpuRegister.Rbp],
            CpuRegister.Rsp => _context[CpuRegister.Rsp],
            CpuRegister.R8 => _context[CpuRegister.R8],
            CpuRegister.R9 => _context[CpuRegister.R9],
            CpuRegister.R10 => _context[CpuRegister.R10],
            CpuRegister.R11 => _context[CpuRegister.R11],
            CpuRegister.R12 => _context[CpuRegister.R12],
            CpuRegister.R13 => _context[CpuRegister.R13],
            CpuRegister.R14 => _context[CpuRegister.R14],
            CpuRegister.R15 => _context[CpuRegister.R15],
            _ => 0
        };

        ulong newValue;
        if (reg == Register.AH || reg == Register.BH || reg == Register.CH || reg == Register.DH)
        {
            newValue = (currentValue & 0xFFFFFFFFFFFF00FF) | ((value & 0xFF) << 8);
        }
        else
        {
            int size = reg.GetSize();
            if (size == 1) newValue = (currentValue & 0xFFFFFFFFFFFFFF00) | (value & 0xFF);
            else if (size == 2) newValue = (currentValue & 0xFFFFFFFFFFFF0000) | (value & 0xFFFF);
            else if (size == 4) newValue = value & 0xFFFFFFFF; // 32-bit ZERO-EXTENDS to 64-bit!
            else newValue = value;
        }

        switch (mapped)
        {
            case CpuRegister.Rax: _context[CpuRegister.Rax] = newValue; break;
            case CpuRegister.Rbx: _context[CpuRegister.Rbx] = newValue; break;
            case CpuRegister.Rcx: _context[CpuRegister.Rcx] = newValue; break;
            case CpuRegister.Rdx: _context[CpuRegister.Rdx] = newValue; break;
            case CpuRegister.Rsi: _context[CpuRegister.Rsi] = newValue; break;
            case CpuRegister.Rdi: _context[CpuRegister.Rdi] = newValue; break;
            case CpuRegister.Rbp: _context[CpuRegister.Rbp] = newValue; break;
            case CpuRegister.Rsp: _context[CpuRegister.Rsp] = newValue; break;
            case CpuRegister.R8: _context[CpuRegister.R8] = newValue; break;
            case CpuRegister.R9: _context[CpuRegister.R9] = newValue; break;
            case CpuRegister.R10: _context[CpuRegister.R10] = newValue; break;
            case CpuRegister.R11: _context[CpuRegister.R11] = newValue; break;
            case CpuRegister.R12: _context[CpuRegister.R12] = newValue; break;
            case CpuRegister.R13: _context[CpuRegister.R13] = newValue; break;
            case CpuRegister.R14: _context[CpuRegister.R14] = newValue; break;
            case CpuRegister.R15: _context[CpuRegister.R15] = newValue; break;
        }
    }

    private CpuRegister MapRegister(Register reg)
    {
        switch (reg)
        {
            case Register.RAX: case Register.EAX: case Register.AX: case Register.AL: case Register.AH: return CpuRegister.Rax;
            case Register.RBX: case Register.EBX: case Register.BX: case Register.BL: case Register.BH: return CpuRegister.Rbx;
            case Register.RCX: case Register.ECX: case Register.CX: case Register.CL: case Register.CH: return CpuRegister.Rcx;
            case Register.RDX: case Register.EDX: case Register.DX: case Register.DL: case Register.DH: return CpuRegister.Rdx;
            case Register.RSI: case Register.ESI: case Register.SI: case Register.SIL: return CpuRegister.Rsi;
            case Register.RDI: case Register.EDI: case Register.DI: case Register.DIL: return CpuRegister.Rdi;
            case Register.RBP: case Register.EBP: case Register.BP: case Register.BPL: return CpuRegister.Rbp;
            case Register.RSP: case Register.ESP: case Register.SP: case Register.SPL: return CpuRegister.Rsp;
            case Register.R8:  case Register.R8D:  case Register.R8W:  case Register.R8L:  return CpuRegister.R8;
            case Register.R9:  case Register.R9D:  case Register.R9W:  case Register.R9L:  return CpuRegister.R9;
            case Register.R10: case Register.R10D: case Register.R10W: case Register.R10L: return CpuRegister.R10;
            case Register.R11: case Register.R11D: case Register.R11W: case Register.R11L: return CpuRegister.R11;
            case Register.R12: case Register.R12D: case Register.R12W: case Register.R12L: return CpuRegister.R12;
            case Register.R13: case Register.R13D: case Register.R13W: case Register.R13L: return CpuRegister.R13;
            case Register.R14: case Register.R14D: case Register.R14W: case Register.R14L: return CpuRegister.R14;
            case Register.R15: case Register.R15D: case Register.R15W: case Register.R15L: return CpuRegister.R15;
            default: throw new NotImplementedException($"Cannot map Iced register {reg} to CpuRegister.");
        }
    }

    /// <summary>
    /// Starts execution from the provided entry point until termination.
    /// </summary>
    /// <param name="entryPoint">The virtual address to begin execution.</param>
    public void Run(ulong entryPoint)
    {
        _context.Rip = entryPoint;
        _context.IsTerminated = false;
        
        Instruction[] traceBuffer = new Instruction[10];
        int traceIndex = 0;
        long instructionCount = 0;

        while (!_context.IsTerminated)
        {
            ulong ripBefore = _context.Rip;
            Instruction currentInstr = default;
            try
            {
                instructionCount++;
                if (instructionCount > 100000000)
                {
                    throw new Exception("Instruction limit reached (infinite loop suspected)");
                }

                var decoder = Decoder.Create(64, new MemoryCodeReader(_memory, ripBefore), ripBefore, DecoderOptions.None);
                decoder.Decode(out currentInstr);
                
                traceBuffer[traceIndex % 10] = currentInstr;
                traceIndex++;
                Step();
            }
            catch (Exception ex)
            {
                var formatter = new NasmFormatter();
                var output = new StringOutput();
                formatter.Format(currentInstr, output);
                
                var sb = new System.Text.StringBuilder();
                sb.AppendLine($"Instruction execution failed: {output.ToString()} at RIP 0x{ripBefore:X}");
                sb.AppendLine($"RAX: 0x{_context[CpuRegister.Rax]:X16} RBX: 0x{_context[CpuRegister.Rbx]:X16} RCX: 0x{_context[CpuRegister.Rcx]:X16}");
                sb.AppendLine("Recent trace:");
                for (int i = 0; i < 10; i++)
                {
                    int idx = (traceIndex - 10 + i);
                    if (idx >= 0)
                    {
                        var tOut = new StringOutput();
                        formatter.Format(traceBuffer[idx % 10], tOut);
                        sb.AppendLine($"  {tOut.ToString()}");
                    }
                }
                sb.AppendLine($"-> {ex.Message}");
                
                throw new Exception(sb.ToString(), ex);
            }
        }
    }

    private bool IsImmediate(OpKind kind)
    {
        return kind == OpKind.Immediate8 || 
               kind == OpKind.Immediate8_2nd ||
               kind == OpKind.Immediate16 ||
               kind == OpKind.Immediate32 ||
               kind == OpKind.Immediate64 ||
               kind == OpKind.Immediate8to16 ||
               kind == OpKind.Immediate8to32 ||
               kind == OpKind.Immediate8to64 ||
               kind == OpKind.Immediate32to64;
    }
}


